# Generated by Django 4.0.1 on 2022-01-14 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('Incident_Dept', models.CharField(max_length=100)),
                ('dateandtime', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('incident_location', models.TextField(max_length=500)),
                ('suspected_cause', models.TextField(max_length=500)),
                ('immediate_action_taken', models.TextField(max_length=500)),
                ('reported_by', models.CharField(default='username', max_length=20)),
            ],
        ),
    ]
