# Generated by Django 4.0.1 on 2022-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_by',
            field=models.CharField(default='username', max_length=20),
        ),
    ]
