# Generated by Django 4.0.1 on 2022-01-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dateandtime',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
