# Generated by Django 4.0.1 on 2022-01-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_report_reported_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='sub_incident_type',
        ),
    ]
