# Generated by Django 4.0.1 on 2022-01-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_report_dateandtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
